# Generated by Django 5.0 on 2023-12-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
