# Generated by Django 5.0 on 2023-12-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_data_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Preço Unitário'),
        ),
    ]
